const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
const html = fs.readFileSync('ott/index.html', 'utf8');
const elements = {};
function element(id) { return elements[id] || (elements[id] = {style: {}, classList: {add() {}, remove() {}}, scrollTop: 0, clientHeight: 600, getBoundingClientRect() { return {top: 175, bottom: 775}; }}); }
assert.ok(!html.includes('data-action="m3uurl"'));
assert.ok(!html.includes('function loadDirectM3u('), 'Client cannot load a custom M3U');
const rows = Array.from({length: 10}, (_, i) => element('row' + i));
const keys = [element('key')];
const ctx = {state: {auth: {}, optIdx: 0}, $: element, document: {documentElement: {clientHeight: 1080}, querySelectorAll: () => keys, getElementsByClassName: () => rows}, window: {}, showToast() {}, saveStorage() {}, detectedPlatform: () => 'NetCast', fetchFeed() {}, renderPlaylistsView() {}, closeOptions() {}, loadPlaylistContent() {}};
vm.createContext(ctx);
function load(name) { const start = html.indexOf('function ' + name + '('); const end = html.indexOf('\nfunction ', start + 1); vm.runInContext(html.slice(start, end), ctx); }
element('topbar').offsetHeight = 175;
load('layoutSettings'); ctx.layoutSettings();
assert.equal(element('view-options').style.top, '175px');
assert.equal(keys[0].style.height, '103px');
ctx.document.documentElement.clientHeight = 720; element('topbar').offsetHeight = 117; ctx.layoutSettings();
assert.equal(element('view-options').style.top, '117px'); assert.equal(keys[0].style.height, '68px');
ctx.OPT_DESCRIPTIONS = []; load('updateOptionsFocus');
rows[0].getBoundingClientRect = () => ({top: 160, bottom: 206}); ctx.updateOptionsFocus();
assert.equal(element('view-options').scrollTop, -23, 'Focused login is scrolled below the HUD');
ctx.state.optIdx = 10; element('btnDoSave').getBoundingClientRect = () => ({top: 760, bottom: 820}); ctx.updateOptionsFocus();
assert.equal(element('view-options').scrollTop, 30, 'Bottom save button is kept visible');
load('doSaveAndLogin'); ctx.state.auth = {login: 'test', password: 'test'};
const pending = []; ctx.apiCall = (...args) => pending.push(args[3]);
ctx.doSaveAndLogin(); ctx.doSaveAndLogin(); assert.equal(pending.length, 1, 'Duplicate login is prevented');
pending.shift()(401, {}); assert.equal(ctx.state.loginBusy, false);
ctx.doSaveAndLogin(); pending.shift()(200, {ok: true, token: 'test'});
assert.equal(ctx.state.loginBusy, true); pending.shift()(0, null); assert.equal(ctx.state.loginBusy, false, 'Device timeout permits retry');
ctx.document.body = element('body'); ctx.applyTheme = () => {}; ctx.updateOptionsDisplay = () => {};
load('applyTextSize'); load('resetPlaybackPreferences');
ctx.state.auth = {token: 'keep-token', login: 'keep-user', deviceId: 'keep-device', theme: 'slate', textSize: 'large', playerEngine: 'html5'};
ctx.state.recentContent = [{id: 'keep-history'}]; ctx.resetPlaybackPreferences();
assert.equal(ctx.state.auth.token, 'keep-token'); assert.equal(ctx.state.auth.login, 'keep-user');
assert.equal(ctx.state.auth.deviceId, 'keep-device'); assert.equal(ctx.state.recentContent[0].id, 'keep-history');
assert.equal(ctx.state.auth.playerEngine, 'auto'); assert.equal(ctx.state.auth.textSize, 'normal');
load('updateTopBar'); ctx.state.screen = 'options'; ctx.state.currentPlaylist = null; ctx.state.channels = []; ctx.state.searchQuery = 'test'; ctx.updateTopBar();
assert.equal(element('topIconsHome').style.display, 'none'); assert.equal(element('topIconsInside').style.display, 'inline-block');
assert.equal(element('btnTitleClear').style.display, 'none');
ctx.state.screen = 'playlists'; ctx.updateTopBar(); assert.equal(element('topIconsHome').style.display, 'inline-block');
load('captureCatalogNavigation'); load('restoreCatalogNavigation');
ctx.state.currentPlaylist = {id: 'a'}; Object.assign(ctx.state, {currentGroup: 'Acción', currentPage: 2, tileIdx: 7, tabIdx: 3, categoryConfirmed: true, currentFocusArea: 'content'});
element('content-area').scrollTop = 100; element('bottom-tabs-bar').scrollLeft = 200;
const saved = ctx.captureCatalogNavigation(); let renders = 0; ctx.renderChannels = () => renders++; ctx.renderTabs = () => {};
ctx.state.currentGroup = 'Comedia'; ctx.state.tileIdx = 0; ctx.restoreCatalogNavigation(saved);
assert.equal(ctx.state.currentGroup, 'Acción'); assert.equal(ctx.state.tileIdx, 7); assert.equal(ctx.state.currentPage, 2); assert.equal(renders, 1);
ctx.state.currentPlaylist = {id: 'b'}; ctx.state.currentGroup = 'Nueva'; ctx.restoreCatalogNavigation(saved); assert.equal(ctx.state.currentGroup, 'Nueva', 'Never restore another playlist');
console.log('Settings: TV layout, login retry, contextual HUD, preferences and catalog return pass.');
