const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const html = fs.readFileSync('ott/index.html', 'utf8');
const start = html.indexOf('function fitTvImage(img)');
const end = html.indexOf('function escapeHtml', start);
const context = {window:{}};
vm.createContext(context);
vm.runInContext('(function(){' + html.slice(start,end) + '})();', context);
assert.equal(typeof context.window.fitTvImage,'function');
const img = {parentNode:{clientWidth:300,clientHeight:200},naturalWidth:400,naturalHeight:225,style:{}};
context.window.img = img;
// 16:9 fast-path fills 100% without layout reflow
vm.runInNewContext('fitTvImage(img)',context.window);
assert.equal(img.style.width,'100%');
assert.equal(img.style.height,'100%');
// 4:3 proportional fit
const img43 = {parentNode:{clientWidth:300,clientHeight:200},naturalWidth:300,naturalHeight:300,style:{}};
context.window.img43 = img43;
vm.runInNewContext('fitTvImage(img43)',context.window);
assert.equal(img43.style.width,'200px');
assert.equal(img43.style.height,'200px');
assert.equal(img43.style.left,'50px');
context.window.fitTvImage(null);
const logo = {parentNode:{clientWidth:200,clientHeight:100},naturalWidth:400,naturalHeight:400,style:{}};
context.window.fitChannelImage(logo);
assert.equal(logo.style.width, '100px');
assert.equal(logo.style.height, '100px');
assert.equal(logo.style.left, '50px');
assert.equal(logo.style.top, '0px');
const wideLogo = {parentNode:{clientWidth:200,clientHeight:100},naturalWidth:400,naturalHeight:100,style:{}};
context.window.fitChannelImage(wideLogo);
assert.equal(wideLogo.style.width, '200px');
assert.equal(wideLogo.style.height, '50px');
assert.equal(wideLogo.style.top, '25px');
assert.equal((html.match(/onload="fitChannelImage\(this\)"/g) || []).length, 2);
console.log('Inline TV image handler resolves globally and preserves proportions.');
